### PR TITLE
#116 Create .clang-format file

### PR DESCRIPTION
**Pull request by MikolajZuzek**
TODO:
- [x] Create initial _.clang-format_ file with style derived from existing source code;
- [ ] Discuss how to organize the workflow to encourage or enforce consistent styling;

### CODE REVIEW

**Comment by MikolajZuzek** [comment]
I derived the style from our source code using https://github.com/mikr/whatstyle, as shown in https://www.youtube.com/watch?v=FNLWtKxXQ0o

This draft contains "preview" changes made using this initial styling and some utility scripts that demonstrate how to reformat the code (maybe that should be in Wiki instead of in the repository).

I found visual editor that we can use to discuss and determine the desired styling: https://zed0.co.uk/clang-format-configurator/
(can load existing styling and live preview the settings)

**Comment by MikolajZuzek** [comment]
One automation option for developers would be to create `pre-commit` git hooks that automatically format the changes to be committed - see [the article](https://www.sandordargo.com/blog/2018/05/30/how-we-format-our-cpp-code) and sample solutions:
* https://github.com/andrewseidl/githook-clang-format
* https://gist.github.com/alexeagle/c8ed91b14a407342d9a8e112b5ac7dab
* https://github.com/barisione/clang-format-hooks

Or we can post instructions on how to configure auto-formatting in popular IDEs.

**Comment by MikolajZuzek** [comment]
@fnrizzi let me know when you decide on the styling (please send _.clang-format_ file) and I'll redo the branch taking it into account.

**Comment by fnrizzi** [comment]
```
BasedOnStyle: google
AlignAfterOpenBracket: AlwaysBreak
AlignConsecutiveAssignments: false
AlignOperands: true
AlignTrailingComments: true
AllowShortFunctionsOnASingleLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakTemplateDeclarations: Yes
BinPackArguments: false
BinPackParameters: false
BreakBeforeBraces: Mozilla
ColumnLimit: 80
CompactNamespaces: false
ConstructorInitializerAllOnOneLineOrOnePerLine: true
ConstructorInitializerIndentWidth: 2
ContinuationIndentWidth: 2
ExperimentalAutoDetectBinPacking: false
Language: Cpp
NamespaceIndentation: None
PenaltyReturnTypeOnItsOwnLine: 0
SpaceAfterTemplateKeyword: true
SpacesInAngles: false
SpacesInParentheses: false
Standard: Cpp11
```
however this is not final, I am having some issues specifying enums and things like that.

**Comment by MikolajZuzek** [comment]
The branch is updated with new _.clang-format_ options. I also reverted reformatting, so that the branch contains only our style file and two helper scripts (easy to remove if we wish them somewhere else) and should be easy to merge into any other branch.

**Comment by MikolajZuzek** [comment]
Checked on closing angle - no good news there. It seems like `template <...>` is still gaining support from auto-formatting tools and they aren't very good at structuring angle brackets yet.  
Example:
```cpp
template< template<class ... T> class Predicate, class Head, class ... Args>
struct none_of<Predicate, Head, Args...>
  : std::conditional <
  Predicate<Head>::type::value,
  std::integral_constant<bool, false>,              //   can we break line(s) here and align closing angles
  typename none_of<Predicate, Args...>::type>::type // <-- with opening statements ?
{};
```
Seems we can't:
* [`clang-format`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html): I was not able to derive suitable options from small sample - like above - using [`whatstyle`](https://github.com/mikr/whatstyle);
* [Artistic Style](https://astyle.sourceforge.net): no option for that, seems to be way behind `clang-format`;
* [Uncrustify](http://uncrustify.sourceforge.net) ([GitHub](https://github.com/uncrustify/uncrustify)): no option for that (see [sample config](https://raw.githubusercontent.com/uncrustify/uncrustify/master/documentation/htdocs/ben.cfg.txt));
* [ReSharper](https://www.jetbrains.com/help/resharper/Languages_CPP.html) (commercial): didn't run it, but the documentation don't mention the capability we seek: [here](https://www.jetbrains.com/help/resharper/EditorConfig_CPP_CppBracesPageScheme.html#resharper_cpp_requires_expression_braces), [here](https://www.jetbrains.com/help/resharper/EditorConfig_CPP_CppWrappingPageScheme.html#resharper_cpp_break_template_declaration) and [here](https://www.jetbrains.com/help/resharper/EditorConfig_CPP_CppOtherPageScheme.html#resharper_cpp_align_multiline_type_parameter).

**Pull request merged**
