### PR TITLE
ops: eigen: revise `min`/`max`

### PR DESCRIPTION
**Pull request by mzuzek**
Contents:
- [x] revised overload constraints
- [x] added missing `subspan` unit test

refs #447

### CODE REVIEW

**Comment by fnrizzi** [comment]
can you plase add to the descvription the table with the various cases like you did here? https://github.com/Pressio/pressio/pull/534#issue-1531145722

**Comment by mzuzek** [comment]
> can you plase add to the descvription the table with the various cases like you did here? [#534 (comment)](https://github.com/Pressio/pressio/pull/534#issue-1531145722)

Thanks @fnrizzi, good point: while doing the table I noticed we're missing matrix test too 😉

**Comment by fnrizzi** [comment]
@mzuzek is this ready?

**Comment by mzuzek** [comment]
> @mzuzek is this ready?

I think so, let me know if you see anything else missing here.

**Review by fnrizzi — APPROVED** [review]

**Comment by mzuzek** [comment]
@fnrizzi thanks for the review!

**Pull request merged**
